apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: okta-oidc
build:
  artifacts:
  - image: okta-oidc # name of the image to be built.
    context: app # directory containing the artifact's sources.
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s
