apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80        # Port accessible inside cluster
      name: http-80
      # targetPort: 80  # Port to forward to inside the pod
      # nodePort: 30002 # Port accessible outside cluster
      # type: LoadBalancer

